config/routes.rb
Rails.application.routes.draw do
  resources :offers

  get 'gateway/index'
  post 'gateway/index'

  get 'gateway/paypal'
  get 'gateway/pago_paypal'
  get 'gateway/dineromail'
  get 'gateway/mercadopago'

  controller :gateway do
    get 'gateway/paypal' => :paypal
    post 'gateway/paypal' => :pago_paypal

  end

  resources :line_items

  resources :carts
  resources :cart

  get 'store/index'
  
  delete 'line_items/' =>'line_items#destroy'

  resources :products do
    resources :offers
  end

  get 'welcome/index'

  resources :module5s

  resources :module4s

  resources :module3s

  resources :module2s

  resources :module1s

  get 'password_resets/new'

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
=begin
  controller :welcome do
    get 'welcome/index' => :new
    post 'welcome/index' => :create
    delete 'welcome/index' => :destroy
    delete 'welcome/logout' => :destroy
  end
=end
  
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :welcome

  resources :users

  resources :rols

  resources :password_resets

  controller :users do
    get 'recover_password' => :recover_password
    post 'recover_password' => :recover_password 
    get 'new_recover_password' => :new_recover_password
    post 'new_recover_password' => :new_recover_password 
    get 'cambiar_password' => :cambiar_password
    post 'cambiar_password' => :cambiar_password
    get 'new_cambiar_password' => :new_cambiar_password
    post 'new_cambiar_password' => :new_cambiar_password
  end 

  root 'store#index', as: 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy


	def add_product(product_id)
		current_item = line_items.find_by(product_id: product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product_id)
		end
		current_item
	end
	def remove_product(product_id)
		current_item = line_items.find_by(product_id: product_id)
		if current_item
			current_item.quantity += -1
		else
			current_item = line_items.build(product_id: product_id)
		end
		current_item
	end
	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart

  def total_price
	product.unit_price * quantity
  end
end

app/models/module1.rb
class Module1 < ActiveRecord::Base
end

app/models/module2.rb
class Module2 < ActiveRecord::Base
end

app/models/module3.rb
class Module3 < ActiveRecord::Base
end

app/models/module4.rb
class Module4 < ActiveRecord::Base
end

app/models/module5.rb
class Module5 < ActiveRecord::Base
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  
  has_one :offer
  before_destroy :ensure_not_referenced_by_any_offer

  validates :title, :description, :image_url, presence: true
  validates :unit_price, numericality: {greater_than_or_equal_to: 0.01}
 
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with:    %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }
  validates :title, length: {minimum: 10}
  
  

  def self.latest
    Product.order(:updated_at).last
  end
  private

    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end

    def ensure_not_referenced_by_any_offer
      if offers.empty?
        return true
      else
        errors.add(:base, 'Offers present')
        return false
      end
    end

    def oferta
      puts "HOLA"
    end

end

app/models/rol.rb
class Rol < ActiveRecord::Base
	has_many :users
	validates :rol_name, 
              presence: true,
            uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true, uniqueness: true
  belongs_to :rol 
  after_destroy :ensure_an_admin_remains
  validates :password, presence: true, length: { in: 6..20 }
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, 
              :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
              :message => ' - El email no es un formato valido.'
  validates :name, :lastname, :rol, presence: true

  def send_password_reset
	  generate_token(:password_reset_token)
	  self.password_reset_sent_at = Time.zone.now
	  save!
	  Mailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  private
	def ensure_an_admin_remains
		if User.count.zero?
			raise "Can't delete last user"
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authorize
  def index
  end

  def new
  end

  def create
  	user = User.find_by(username: params[:username])
  	if user and user.authenticate(params[:password])
  		session[:user_id] = user.id
  		session[:uname] = user.name + " " + user.lastname
  		session[:rol_id] = user.rol_id
      puts "Hola" + user.name + " " + user.lastname

      #variables de rol
      rol =Rol.find_by(id: user.rol_id)
      session[:mod0] =rol.admin
      session[:mod1] =rol.module_1
      session[:mod2] =rol.module_2
      session[:mod3] =rol.module_3
      session[:mod4] =rol.module_4
      session[:mod5] =rol.module_5
      #termina variables de rol


      unless session[:lasurl].nil? || session[:lasurl].empty?
  		  #redirect_to session[:lasurl]
        redirect_to store_url
      else 
        redirect_to "login"
      end

  	else
  		redirect_to "login", alert: "Invalid user/password combination"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to login_url, notice: "Logged out"
  end



end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/gateway_helper.rb
module GatewayHelper
end

app/helpers/module1s_helper.rb
module Module1sHelper
end

app/helpers/module2s_helper.rb
module Module2sHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h1>User Login</h1>

<%= render "sessions/new" %>

app/views/welcome/index2.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>TBF</title>
    <script type="text/javascript" src="code/js/rollover.js"></script>
    <link rel="STYLESHEET" type="text/css" href="code/css/estilo_index.css">  
</head>

<body>
	<div id="contenido">
		<div id="bloque_1">
        	<img src="images/bloque_1.png" width="320" height="320" />
		</div>
		<div id="bloque_2">
			<div id="bloque_2_1" class="bloque_2">
 				<% unless User.find_by(id: session[:user_id]) %>
					<%= form_tag do %>
						<% if flash[:alert] %>
							<p id="notice"><%= flash[:alert] %></p>
						<% end %>
						<div>
							<%= label_tag :username, 'Name:' %> </br>
							<%= text_field_tag :username, params[:username] %>
						</div>
						<div>
							<%= label_tag :password, 'Password:' %></br>
							<%= password_field_tag :password, params[:password] %>
						</div>
						<div>
							<%= submit_tag "Login" %>
						</div>
					<% end %>

						<div>
							<%#= link_to "Recuperar Password", new_recover_password_path %>
							<p><%= link_to "forgotten password?", new_password_reset_path %></p>
							
						</div>
				<% else %>
					<p>Bienvenido <%= "#{session[:uname]}"%></p>
					<%= link_to "Cambiar Password", new_cambiar_password_path %>
					<%= button_to 'Logout', logout_path, method: :delete %>
				<%end %>
			</div>        
		</div>
		<div id="bloque_3">
			<div id="bloque_3_1" class="bloque_3"> 
            <span class="info_bloque3_1">
            www.tbf.mx<br />
      		info@tbf.mx<br />
     		T.(81) 2086.0032<br /></span> 
  			<span class="info_bloque3_2">
                Monterrey, M&eacute;xico </span>
            </div>        
		</div>
		<div id="bloque_4">
		  <div id="bloque_4_1" class="contenido_bloques"> 
           <span class="titulos_bloques">Desarrollo <br />
           Web:</span> <span class="subtitulos_bloques">Ruby on Rails </span></div>          
        </div>
		<div id="bloque_5">
 			<div id="bloque_5_1" class="contenido_bloques"> 
            <span class="titulos_bloques">
            Realidad <br />
			Aumentada</span> 
            </div>         
		</div>
		<div id="bloque_6">
 			<div id="bloque_6_1" class="contenido_bloques"> 
            <span class="titulos_bloques">
            M&oacute;dulos<br />
            Interactivos</span> 
            </div>         
		</div>
		<div id="bloque_7">
 			<div id="bloque_7_1" class="contenido_bloques"> 
            <span class="titulos_bloques">
            Video<br />
            Mapping</span> 
            </div>         
		</div>
		<div id="bloque_8">
            
		</div>    
		<div id="bloque_9">
		</div>                                                            
	</div>
</body>
</html>